# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Publish to npm

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: ğŸ§© Install dependencies
        run: npm ci
      - name: âœ… Testing
        run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: ğŸ§© Install dependencies
        run: npm ci

      - name: ğŸ“¦ Build dist folder
        run: npm run build

      - name: ğŸ¯ Get target version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: ğŸš€ Publish package
        run: npm run publish --tag ${{ steps.get_version.outputs.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
